let TIMEOUT = 120000,
    PHANTOM_TIMEOUT = 90000,
    SERVER_REJECT_SLEEP = 333,
    SPLIT_LIMIT = 40;

// Test Config
// TIMEOUT = 0,
// PHANTOM_TIMEOUT = 500;
// SERVER_REJECT_SLEEP = 333;
// SPLIT_LIMIT = 4;

module.exports = {
  TIMEOUT,
  PHANTOM_TIMEOUT,
  SERVER_REJECT_SLEEP,
  SPLIT_LIMIT
}
